version: "3.8"

services:
  luffytv-api:
    build: .
    container_name: luffytv-api
    environment:
      - PORT=3000
      - CACHE_TTL=3600000
    ports:
      - "3000:3000"
    restart: unless-stopped
